version: "3.3"

services:
  database:
    container_name: db_silen2festation
    build: ./psql_database
    restart: always
    ports:
      - "5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DEV_DB_NAME}
    networks:
      - silen2festation
    volumes:
      - postgres_data:/var/lib/postgresql/data

  website:
    depends_on:
      - database
    container_name: website_silen2festation
    working_dir: /usr/src/app
    image: ${DOCKER_USERNAME}/silent-infestation:latest
    restart: always
    env_file:
      - .env.prod
    networks:
      - silen2festation
    ports:
      - "${PORT_FRONT}:3000"
    volumes:
      - ./website_next:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    command: >
      sh -c "./wait-for-it.sh db_silen2festation:5432 -- npx prisma migrate deploy && npx prisma db seed && npm run start"

networks:
  silen2festation:

volumes:
  postgres_data:
