# Build du projet
FROM node:18-alpine AS build

ENV NODE_ENV=dev

WORKDIR /usr/src/app

COPY package.json .
RUN npm install

COPY . .

RUN apk update && apk add --no-cache bash

EXPOSE 3000

CMD ["npm", "run", "dev"]
