# Build du projet
FROM node:20-alpine AS build

ENV NODE_ENV=dev

WORKDIR /usr/src/app

COPY package.json .

COPY . .

RUN npm install

RUN apk update && apk add --no-cache bash

RUN npx prisma generate

# RUN npm run build

EXPOSE 23000

CMD ["npm", "run", "dev"]