# Build du projet
FROM node:20-alpine AS build

ENV NODE_ENV=dev

WORKDIR /usr/src/app

COPY package.json .

RUN npm install

COPY . .

RUN apk update && apk add --no-cache bash

RUN npx prisma generate

RUN npx prettier --write .

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "dev"]