FROM node:20-alpine AS build

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm ci

COPY . .

RUN npx prisma generate --schema=prisma/schema.prisma
RUN npm run build

RUN rm -rf .next/cache
RUN npm prune --production

# Étape 2 : Création de l'image de production
FROM node:20-alpine

ENV NODE_ENV=production
WORKDIR /usr/src/app

COPY --from=build /usr/src/app ./

RUN apk add --no-cache bash

EXPOSE 3000

CMD ["npm", "run", "start"]